### ISSUE TITLE
Memory leak in pixForImage

### ISSUE THREAD

**Issue by chargeflux** [scott0123/Tesseract-macOS#3] opened 2018-11-19 01:26 UTC
I noticed there is a memory leak occurring in `pixForImage`. XCode's Memory debugger seems to point to Line 230 in `SLTesseract.mm` as the culprit and it happens in your Screenshot app and in mine. I haven't identified what exactly is being retained, e.g., `pix`, `cg` or something else, but you do run ` pixDestroy(&pix);` in Line 172 of the same file. Do you have any ideas?

On a side note, I believe `tesseract::ResultIterator* ri` in `getClassiferChoicesPerSymbol` is not being cleared and causes a memory leak so adding `delete ri;` after Line 146 in `SLTesseract.mm` seems to solve the issue. I can submit a quick PR if need be.

**Comment by scott0123** [comment] 2018-11-19 04:47
Yes. I remember noticing that too. `pixDestroy(&pix);` was my attempt at fixing that memory leak. But I guess that didn't help too much. We should try and diagnose this problem a bit further, perhaps by observing what is actually being retained and trying to free that.

Regarding the `ResultIterator*` pointer fix, submit a PR so it count as your contribution since you discovered that.

**Comment by scott0123** [comment] 2018-11-19 19:11
Something is causing a leak from the `setEngineImage` function.
Possible candidates
- `pix = [self pixForImage:image];` on line 162.
- `_tesseract->SetImage(pix);` on line 165.
- `pixDestroy(&pix);` on line 172.

Here's a screenshot of the leak happening:
<img width="670" alt="leak" src="https://user-images.githubusercontent.com/29332207/48729177-96daae80-ebfc-11e8-91a7-44f65d36a357.png">

If you have time, feel free to investigate this further.

**Comment by chargeflux** [comment] 2018-11-20 04:40
I did some more debugging and I think the issue can be narrowed down to `_tesseract->SetImage(pix)` in line 165. This might be relevant: https://github.com/gali8/Tesseract-OCR-iOS/issues/59. I will look into how they solved their issue later.

In the documentation for `SetImage`: 
> Provide an image for Tesseract to recognize. As with SetImage above, Tesseract takes its own copy of the image, so it need not persist until after Recognize...

I wonder if Tesseract disposes of that "copy" it makes. If it doesn't, then it might explain the memory leak. I don't think the pix we create is an issue since we destroy it immediately after with `pixDestroy` in line 172.

**Comment by chargeflux** [comment] 2018-11-21 04:49
I think I narrowed down the issue significantly.

If I comment out the following lines in SLTesseract.mm in the `pixForImage` function,

> pixels = (l_uint32 *) malloc(width * height * sizeof(l_uint32)); // Line 220
> memset(pixels, 0, width * height * sizeof(l_uint32)); // Line 221
> pixSetData(pix, pixels); // Line 232

the leak doesn't happen but OCR Recognition seemingly doesn't occur either. 

Uncommenting the above lines, setting `pixels` to nullptr after Line 233 doesn't stop the leak. Any thoughts on how to resolve? 

This may be unrelated but the program still works fine with recognition (but has the leak) if you comment out the memset line.

**Comment by scott0123** [comment] 2018-11-21 06:01
I think you might be on to something when you said
> I wonder if Tesseract disposes of that "copy" it makes
because that is the only conceivable place where the memory leak could happen.

As for your second latest comment, sure that is the fundamental cause of the leak as some of the `malloc`ed space was never given a corresponding `free`. However, this doesn't really help us in terms of arriving at a resolution.

My suspicion is that when we call `_tesseract->SetImage(pix);` on line 166, another `Pix` object might be allocated by the SetImage function (which we cannot control). If this hypothesis holds true, then we may either have to figure out if there is a corresponding tesseract function that lets us free this malloced space, or look at how the iOS port of Tesseract has solved the similar issue.

**Comment by scott0123** [comment] 2018-11-21 06:11
As for the `memset`, all that function is doing is clearing the newly `malloc`ed heap space to all zeros.

Technically the code between line 221 and 232 should completely replace whatever garbage was already in the newly `malloc`ed location, but this `memset` would guarantee that even should the code in-between fail, the pix wouldn't literally be a hunk of garbage which is later read by unsuspecting functions. 

This is also a security measure in this sense, as it may be theoretically possible for a malicious user to somehow trigger unexpected behavior if they can somehow manipulate the heap memory in a special way. This would be effectively prevented if `memcpy` was used to clear it.

**Comment by pware2015** [comment] 2019-04-01 22:36
The memory leak can be fixed by inserting the line:
pixFreeData(pix);

Before the line:
pixSetData(pix, pixels);

pixCreate() in Leptonica allocates memory for data in the Pix struct according to the dimensions and bpp passed in, and calling pixSetData() does not automatically free what it allocated before updating the pointer, which causes the leak.

**Comment by scott0123** [comment] 2019-04-01 22:50
Thank you for your input on this matter @pware2015.
I have updated the code according to this feedback, I'm glad it was a straightforward fix.
See commit 60f97ef

References:
    https://tpgit.github.io/Leptonica/pix1_8c.html
    https://android.googlesource.com/platform/external/tesseract/+/master/liblept/pix1.c

**Closed as completed** 2019-04-01 22:50 UTC

**Comment by chargeflux** [comment] 2019-04-01 23:01
Nice @pware2015! I can confirm this fixes the leak with `pix` in my app. I don't know about the Screenshot utility in this repo as I can't build it on Mojave but I have no reason to think it wouldn't fix the issue there as well.

**Comment by scott0123** [comment] 2019-04-01 23:06
The screenshot utility was just hacked together as a fast way to showcase / verify the OCR capabilities.

Personally, I have opted to not upgrade to Mojave as of yet so I have no idea why the build would be broken there.

If this is an issue please open a separate thread. Thanks.
